# Python Program for wishing friends "Happy Birthday"

import turtle
from turtle import *
from turtle import Turtle, Screen
from math import sin, pi

TURTLE_SIZE = 20

screen = Screen()

jb = Turtle(shape="turtle", visible=False)
jb.penup()
jb.goto(TURTLE_SIZE/2 - screen.window_width()/2,
        screen.window_height() / 2 - TURTLE_SIZE / 2)
jb.pendown()
jb.showturtle()
jb.pensize(5)
jb.speed(10)


def happy():
    def h():
        jb.color("black", "red")
        jb.begin_fill()
        jb.right(90)
        jb.forward(120)
        jb.left(90)
        jb.forward(20)
        jb.left(90)
        jb.forward(50)
        jb.right(90)
        jb.forward(40)
        jb.right(90)
        jb.forward(50)
        jb.left(90)
        jb.forward(20)
        jb.left(90)
        jb.forward(120)
        jb.left(90)
        jb.forward(20)
        jb.left(90)
        jb.forward(50)
        jb.right(90)
        jb.forward(40)
        jb.right(90)
        jb.forward(50)
        jb.left(90)
        jb.forward(20)
        jb.end_fill()
        jb.up()
        jb.right(180)
        jb.forward(140)
        jb.down()

    def a():
        jb.color("black", "red")
        jb.begin_fill()
        jb.forward(20)
        jb.right(60)
        jb.forward(138)
        jb.right(120)
        jb.forward(20)
        jb.right(60)
        jb.forward(115)
        jb.left(130)
        jb.forward(115)
        jb.right(60)
        jb.forward(20)
        jb.right(120)
        jb.forward(142)
        jb.end_fill()
        jb.up()
        jb.right(70)
        jb.forward(100)
        jb.down()

    def p():
        jb.color("black", "red")
        jb.begin_fill()
        jb.forward(80)
        jb.right(90)
        jb.forward(60)
        jb.right(90)
        jb.forward(60)
        jb.left(90)
        jb.forward(60)
        jb.right(90)
        jb.forward(20)
        jb.right(90)
        jb.forward(120)
        jb.up()
        jb.right(90)
        jb.forward(20)
        jb.right(90)
        jb.forward(20)
        jb.left(90)
        jb.down()
        jb.end_fill()
        jb.color("black", "white")
        jb.begin_fill()
        jb.forward(40)
        jb.right(90)
        jb.forward(20)
        jb.right(90)
        jb.forward(40)
        jb.right(90)
        jb.forward(20)
        jb.end_fill()
        jb.up()
        jb.forward(20)
        jb.right(90)
        jb.forward(70)
        jb.color(0, 0, 1)
        jb.down()

    def y():
        jb.color("black", "red")
        jb.begin_fill()
        jb.right(45)
        jb.forward(90)
        jb.right(45)
        jb.forward(70)
        jb.left(90)
        jb.forward(20)
        jb.left(90)
        jb.forward(70)
        jb.right(45)
        jb.forward(90)
        jb.left(135)
        jb.forward(25)
        jb.left(45)
        jb.forward(70)
        jb.right(90)
        jb.forward(70)
        jb.left(45)
        jb.forward(25)
        jb.end_fill()

    h()
    a()
    p()
    p()
    y()


def birthday():
    def b():
        jb.color("black", "deeppink1")
        jb.begin_fill()
        jb.forward(80)
        jb.right(90)
        jb.forward(50)
        jb.right(60)
        jb.forward(40)
        jb.left(120)
        jb.forward(40)
        jb.right(60)
        jb.forward(50)
        jb.right(90)
        jb.forward(80)
        jb.right(90)
        jb.forward(20)
        jb.right(90)
        jb.forward(20)
        jb.left(90)
        jb.forward(100)
        jb.left(90)
        jb.forward(20)
        jb.right(90)
        jb.forward(20)
        jb.right(90)
        jb.up()
        jb.forward(40)
        jb.right(90)
        jb.forward(20)
        jb.down()
        jb.end_fill()
        jb.color("black", "white")
        jb.begin_fill()
        jb.forward(30)
        jb.left(90)
        jb.forward(10)
        jb.left(30)
        jb.forward(20)
        jb.left(60)
        jb.forward(20)
        jb.left(90)
        jb.forward(27)
        jb.left(90)
        jb.forward(10)
        jb.end_fill()
        jb.up()
        jb.forward(50)
        jb.down()
        jb.begin_fill()
        jb.forward(40)
        jb.left(90)
        jb.forward(30)
        jb.left(90)
        jb.forward(20)
        jb.left(65)
        jb.forward(35)
        jb.end_fill()
        jb.left(25)
        jb.left(90)
        jb.up()
        jb.forward(55)
        jb.left(90)
        jb.forward(75)
        jb.left(90)
        jb.forward(135)
        jb.right(90)
        jb.down()

    def i():
        jb.color("black", "deeppink1")
        jb.begin_fill()
        jb.forward(90)
        jb.right(90)
        jb.forward(30)
        jb.right(90)
        jb.forward(30)
        jb.left(90)
        jb.forward(75)
        jb.left(90)
        jb.forward(30)
        jb.right(90)
        jb.forward(30)
        jb.right(90)
        jb.forward(90)
        jb.right(90)
        jb.forward(30)
        jb.right(90)
        jb.forward(30)
        jb.left(90)
        jb.forward(75)
        jb.left(90)
        jb.forward(30)
        jb.right(90)
        jb.forward(30)
        jb.end_fill()
        jb.up()
        jb.right(90)
        jb.forward(120)  # edit spacing
        jb.down()

    def r():
        jb.color("black", "deeppink1")
        jb.begin_fill()
        jb.right(90)
        jb.forward(120)
        jb.left(90)
        jb.forward(20)
        jb.left(90)
        jb.forward(60)
        jb.right(140)
        jb.forward(80)
        jb.left(90)
        jb.forward(20)
        jb.left(90)
        jb.forward(70)
        jb.right(130)
        jb.forward(30)
        jb.left(90)
        jb.forward(60)
        jb.left(90)
        jb.forward(70)
        jb.end_fill()
        jb.color("black", "white")
        jb.up()
        jb.right(180)
        jb.forward(15)
        jb.right(90)
        jb.forward(45)
        jb.down()
        jb.begin_fill()
        for i in range(1, 5):
            jb.left(90)
            jb.forward(30)
        jb.end_fill()
        jb.up()
        jb.right(180)
        jb.forward(45)
        jb.right(90)
        jb.forward(100)  # edit spacing
        jb.down()

    def t():
        jb.color("black", "deeppink1")
        jb.begin_fill()
        jb.forward(100)
        jb.right(90)
        jb.forward(20)
        jb.right(90)
        jb.forward(40)
        jb.left(90)
        jb.forward(100)
        jb.right(90)
        jb.forward(20)
        jb.right(90)
        jb.forward(100)
        jb.left(90)
        jb.forward(40)
        jb.right(90)
        jb.forward(20)
        jb.end_fill()
        jb.up()
        jb.right(90)
        jb.forward(120)  # edit spacing
        jb.down()

    def h():
        jb.color("black", "deeppink1")
        jb.begin_fill()
        jb.right(90)
        jb.forward(120)
        jb.left(90)
        jb.forward(20)
        jb.left(90)
        jb.forward(50)
        jb.right(90)
        jb.forward(40)
        jb.right(90)
        jb.forward(50)
        jb.left(90)
        jb.forward(20)
        jb.left(90)
        jb.forward(120)
        jb.left(90)
        jb.forward(20)
        jb.left(90)
        jb.forward(50)
        jb.right(90)
        jb.forward(40)
        jb.right(90)
        jb.forward(50)
        jb.left(90)
        jb.forward(20)
        jb.end_fill()
        jb.up()
        jb.right(180)
        jb.forward(110)  # edit spacing
        jb.down()

    def d():
        jb.color("black", "dodgerblue1")
        jb.begin_fill()
        jb.forward(100)
        jb.right(90)
        jb.forward(120)
        jb.right(90)
        jb.forward(100)
        jb.right(90)
        jb.forward(20)
        jb.right(90)
        jb.forward(20)
        jb.left(90)
        jb.forward(80)
        jb.left(90)
        jb.forward(20)
        jb.right(90)
        jb.forward(20)
        jb.end_fill()
        jb.up()
        jb.right(90)
        jb.forward(40)
        jb.right(90)
        jb.forward(30)
        jb.right(90)
        jb.color("black", "white")
        jb.down()
        jb.begin_fill()
        for i in range(1, 5):
            jb.left(90)
            jb.forward(55)
            jb.left(90)
            jb.forward(40)
        jb.end_fill()
        jb.up()
        jb.right(90)
        jb.forward(30)
        jb.right(90)
        jb.forward(110)  # edit spacing
        jb.down()

    def a():
        jb.color("black", "dodgerblue1")
        jb.begin_fill()
        jb.forward(20)
        jb.right(60)
        jb.forward(138)
        jb.right(120)
        jb.forward(20)
        jb.right(60)
        jb.forward(115)
        jb.left(130)
        jb.forward(115)
        jb.right(60)
        jb.forward(20)
        jb.right(120)
        jb.forward(142)
        jb.end_fill()
        jb.up()
        jb.right(70)
        jb.forward(80)  # edit spacing
        jb.down()

    def y():
        jb.color("black", "dodgerblue1")
        jb.begin_fill()
        jb.right(45)
        jb.forward(90)
        jb.right(45)
        jb.forward(70)
        jb.left(90)
        jb.forward(20)
        jb.left(90)
        jb.forward(70)
        jb.right(45)
        jb.forward(90)
        jb.left(135)
        jb.forward(25)
        jb.left(45)
        jb.forward(70)
        jb.right(90)
        jb.forward(70)
        jb.left(45)
        jb.forward(25)
        jb.end_fill()
    b()
    i()
    r()
    t()
    h()
    d()
    a()
    y()


def james():
    def My_heart():
        def heart(size, shape):
            jb.pensize(2)
            radius = size * sin(shape * pi / 180) / \
                (1 + sin(90 - shape) * pi / 180)
            jb.right(shape)
            jb.forward(size)
            jb.circle(radius, 180 + shape)
            jb.right(180)
            jb.circle(radius, 180 + shape)
            jb.forward(size)
            jb.left(180 - shape)
        jb.color("black", "red")
        # jb.color(1,0,0)
        jb.left(90)
        jb.begin_fill()
        heart(30, 30)
        jb.end_fill()

    def j():
        jb.up()
        jb.forward(150)
        jb.right(90)
        jb.forward(100)
        jb.left(90)
        jb.down()
        jb.color("black", "mediumorchid")
        jb.begin_fill()
        jb.right(90)
        jb.forward(30)
        jb.right(90)
        jb.forward(45)
        jb.right(45)
        jb.forward(20)
        jb.right(45)
        jb.forward(10)
        jb.right(90)
        jb.forward(20)
        jb.right(45)
        jb.forward(10)
        jb.left(45)
        jb.forward(15)
        jb.left(90)
        jb.forward(60)
        jb.left(90)
        jb.forward(40)
        jb.right(90)
        jb.forward(20)
        jb.right(90)
        jb.forward(75)
        jb.right(90)
        jb.forward(20)
        jb.right(90)
        jb.forward(18)
        jb.left(90)
        jb.forward(60)
        jb.end_fill()
        jb.up()
        jb.right(180)
        jb.forward(80)
        jb.right(90)
        jb.forward(40)
        jb.down()

    def a():
        jb.color("black", "mediumorchid")
        jb.begin_fill()
        jb.forward(20)
        jb.right(60)
        jb.forward(138)
        jb.right(120)
        jb.forward(20)
        jb.right(60)
        jb.forward(115)
        jb.left(130)
        jb.forward(115)
        jb.right(60)
        jb.forward(20)
        jb.right(120)
        jb.forward(142)
        jb.end_fill()
        jb.up()
        jb.right(70)
        jb.forward(90)  # edit spacing
        jb.down()

    def m():
        jb.up()
        jb.right(90)
        jb.down()
        jb.color("black", "mediumorchid")
        jb.begin_fill()
        jb.forward(75)
        jb.left(90)
        jb.forward(15)
        jb.left(90)
        jb.forward(45)
        jb.right(135)
        jb.forward(35)
        jb.left(90)
        jb.forward(35)
        jb.right(135)
        jb.forward(45)
        jb.left(90)
        jb.forward(15)
        jb.left(90)
        jb.forward(75)
        jb.left(90)
        jb.forward(75)
        jb.end_fill()
        jb.up()
        jb.right(180)
        jb.forward(95)
        jb.down()

    def e():
        jb.color("black", "mediumorchid")
        jb.begin_fill()
        jb.right(90)
        jb.forward(75)
        jb.left(90)
        jb.forward(60)
        jb.left(90)
        jb.forward(15)
        jb.left(90)
        jb.forward(30)
        jb.right(90)
        jb.forward(15)
        jb.right(90)
        jb.forward(30)
        jb.left(90)
        jb.forward(15)
        jb.left(90)
        jb.forward(30)
        jb.right(90)
        jb.forward(15)
        jb.right(90)
        jb.forward(30)
        jb.left(90)
        jb.forward(15)
        jb.left(90)
        jb.forward(60)
        jb.end_fill()
        jb.up()
        jb.right(180)
        jb.forward(80)
        jb.down()

    def s():
        jb.color("black", "mediumorchid")
        jb.begin_fill()
        jb.right(90)
        jb.forward(45)
        jb.left(90)
        jb.forward(30)
        jb.right(90)
        jb.forward(15)
        jb.right(90)
        jb.forward(30)
        jb.left(90)
        jb.forward(15)
        jb.left(90)
        jb.forward(60)
        jb.left(90)
        jb.forward(45)
        jb.left(90)
        jb.forward(30)
        jb.right(90)
        jb.forward(15)
        jb.right(90)
        jb.forward(30)
        jb.left(90)
        jb.forward(15)
        jb.left(90)
        jb.forward(60)
        jb.end_fill()
        jb.up()
        jb.forward(400)
        jb.left(90)
        jb.forward(75)
        jb.left(90)
        jb.down()

    j()
    a()
    m()
    e()
    s()
    My_heart()
    jb.pensize(5)
    jb.up()
    jb.color(0, 0, 0)
    jb.right(90)
    jb.down()
    jb.forward(575)
    My_heart()


# This moves it back to the left side of the screen to write
happy()
jb.up()
jb.left(90)
jb.forward(250)
jb.right(90)
jb.forward(400)
jb.right(180)
jb.down()

birthday()
jb.up()
jb.left(90)
jb.forward(250)
jb.right(90)
jb.forward(650)
jb.right(180)
jb.down()

james()


screen.mainloop()
